// Generated by CoffeeScript 1.8.0
(function() {
  var boothApp,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  boothApp = angular.module('judgebooth', ['ionic', 'angular-cache', 'pascalprecht.translate', 'boothServices']);

  boothApp.config([
    '$locationProvider', '$stateProvider', '$urlRouterProvider', function($locationProvider, $stateProvider, $urlRouterProvider) {
      $locationProvider.html5Mode(!ionic.Platform.isWebView());
      $stateProvider.state('home', {
        url: '/',
        templateUrl: 'views/home.html',
        controller: 'HomeCtrl',
        resolve: {
          questions: [
            'questionsAPI', function(questionsAPI) {
              return questionsAPI.questions();
            }
          ],
          sets: [
            'questionsAPI', function(questionsAPI) {
              return questionsAPI.sets();
            }
          ]
        }
      }).state('question', {
        url: '/question/:id',
        templateUrl: 'views/question.html',
        controller: 'QuestionCtrl'
      });
      return $urlRouterProvider.otherwise('/');
    }
  ]);

  boothApp.run([
    'questionsAPI', '$rootScope', '$state', function(questionsAPI, $rootScope, $state) {
      $rootScope.$on('$stateChangeSuccess', function(event, toState) {
        return $rootScope.state = toState;
      });
      return $rootScope.next = function() {
        return questionsAPI.nextQuestion().then(function(id) {
          return $state.go("question", {
            id: id
          });
        });
      };
    }
  ]);

  boothApp.controller('SideCtrl', [
    "$scope", "questionsAPI", function($scope, questionsAPI) {
      $scope.filter = questionsAPI.filter();
      $scope.languages = questionsAPI.languages();
      $scope.languageCounts = {};
      questionsAPI.sets().then(function(response) {
        return $scope.sets = response.data;
      });
      questionsAPI.questions().then(function(response) {
        var card, language, question, set, sets, _base, _base1, _base2, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref, _ref1, _ref2;
        $scope.questions = response.data;
        $scope.setCounts = {};
        _ref = $scope.questions;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          question = _ref[_i];
          sets = [];
          _ref1 = question.cards;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            card = _ref1[_j];
            for (_k = 0, _len2 = card.length; _k < _len2; _k++) {
              set = card[_k];
              if (__indexOf.call(sets, set) < 0) {
                sets.push(set);
              }
            }
          }
          _ref2 = question.languages;
          for (_l = 0, _len3 = _ref2.length; _l < _len3; _l++) {
            language = _ref2[_l];
            (_base = $scope.languageCounts)[language] || (_base[language] = 0);
            $scope.languageCounts[language]++;
            for (_m = 0, _len4 = sets.length; _m < _len4; _m++) {
              set = sets[_m];
              (_base1 = $scope.setCounts)[language] || (_base1[language] = {});
              (_base2 = $scope.setCounts[language])[set] || (_base2[set] = 0);
              $scope.setCounts[language][set]++;
            }
          }
        }
        return $scope.updateCount();
      });
      $scope.toggleSet = function(id) {
        var set, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
        if (id === "all" || id === "modern" || id === "standard" || id === "none") {
          $scope.filter.sets = [];
        }
        switch (id) {
          case "standard":
            _ref = $scope.sets;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              set = _ref[_i];
              if (!set.standard) {
                $scope.filter.sets.push(set.id);
              }
            }
            break;
          case "modern":
            _ref1 = $scope.sets;
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              set = _ref1[_j];
              if (!set.modern) {
                $scope.filter.sets.push(set.id);
              }
            }
            break;
          case "none":
            _ref2 = $scope.sets;
            for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
              set = _ref2[_k];
              $scope.filter.sets.push(set.id);
            }
            break;
          default:
            if (__indexOf.call($scope.filter.sets, id) >= 0) {
              $scope.filter.sets.splice($scope.filter.sets.indexOf(id), 1);
            } else {
              $scope.filter.sets.push(id);
            }
        }
        return $scope.updateCount();
      };
      $scope.toggleDifficulty = function(level) {
        if (__indexOf.call($scope.filter.difficulty, level) >= 0) {
          $scope.filter.difficulty.splice($scope.filter.difficulty.indexOf(level), 1);
        } else {
          $scope.filter.difficulty.push(level);
        }
        return $scope.updateCount();
      };
      $scope.updateCount = function() {
        var set, _i, _len, _ref, _results;
        questionsAPI.filterQuestions($scope.filter, false).then(function(questions) {
          return $scope.filteredQuestions = questions;
        });
        $scope.setCount = Object.keys($scope.setCounts[$scope.filter.language]).length;
        _ref = $scope.filter.sets;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          set = _ref[_i];
          if ($scope.setCounts[$scope.filter.language][set]) {
            _results.push($scope.setCount--);
          }
        }
        return _results;
      };
      return $scope.showQuestions = function() {
        if (!$scope.filteredQuestions.length) {
          return;
        }
        questionsAPI.filter($scope.filter);
        return $scope.next();
      };
    }
  ]);

  boothApp.controller('HomeCtrl', [
    "$scope", "questions", "sets", function($scope, questions, sets) {
      $scope.questions = questions.data;
      return $scope.sets = sets.data;
    }
  ]);

  boothApp.controller('QuestionCtrl', [
    "$scope", "questionsAPI", "$stateParams", "$state", "$ionicScrollDelegate", function($scope, questionsAPI, $stateParams, $state, $ionicScrollDelegate) {
      var gatherer;
      gatherer = 'http://gatherer.wizards.com/Handlers/Image.ashx?type=card&name=';
      questionsAPI.question($stateParams.id).then(function(question) {
        var card, _i, _len, _ref, _ref1;
        $scope.question = question;
        _ref = question.cards;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          card = _ref[_i];
          card.src = gatherer + card.name;
          if (card.layout === "split") {
            card.src = gatherer + card.full_name;
          }
          if (card.url) {
            card.src = card.url;
          }
          card.manacost = (card.manacost || "").replace(/\{([wubrg0-9]+)\}/ig, function(a, b) {
            return "<i class='mtg mana-" + (b.toLowerCase()) + "'></i>";
          }).replace(/\{([2wubrg])\/([wubrg])\}/ig, function(a, b, c) {
            return "<i class='mtg hybrid-" + ((b + c).toLowerCase()) + "'></i>";
          });
          card.text = (card.text || "").replace(/\{([wubrg0-9]+)\}/ig, function(a, b) {
            return "<i class='mtg mana-" + (b.toLowerCase()) + "'></i>";
          }).replace(/\{t\}/ig, "<i class='mtg tap'></i>").replace(/\{q\}/ig, "<i class='mtg untap'></i>").replace(/\{([2wubrg])\/([wubrg])\}/ig, function(a, b, c) {
            return "<i class='mtg hybrid-" + ((b + c).toLowerCase()) + "'></i>";
          }).replace(/(\(.*?\))/ig, '<em>$1</em>');
          question.question = question.question.replace(RegExp("(" + card.name + ")", "ig"), "<b>$1</b>");
          question.answer = question.answer.replace(RegExp("(" + card.name + ")", "ig"), "<b>$1</b>");
        }
        if (!((_ref1 = question.metadata) != null ? _ref1.id : void 0)) {
          return $state.go("home");
        }
      });
      return $scope.toggleAnswer = function() {
        $scope.answer = !$scope.answer;
        $ionicScrollDelegate.resize();
        return $ionicScrollDelegate.scrollBottom(true);
      };
    }
  ]);

  boothApp.directive('ngLoad', [
    '$parse', function($parse) {
      return {
        restrict: 'A',
        compile: function($element, attr) {
          var fn;
          fn = $parse(attr['ngLoad']);
          return function(scope, element, attr) {
            return element.on('load', function(event) {
              return scope.$apply(function() {
                return fn(scope, {
                  $event: event
                });
              });
            });
          };
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=app.js.map
